version: '3.8'

services:
  postgres-ielts:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ielts_database
    ports:
      - "5434:5432"
    volumes:
      - postgres_ielts_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-user:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_database
    ports:
      - "5435:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:alpine"
    ports:
      - "6369:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  bonus-user-db:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - bonus_user_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  integration-service:
    build:
      context: ./integration-service
      dockerfile: Dockerfile
    ports:
      - "50053:50053"
    restart: unless-stopped

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "50054:50054"
    environment:
      - DB_HOST=postgres-user
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=user_database
    depends_on:
      postgres-user:
        condition: service_healthy
    restart: unless-stopped

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment:
      - DB_HOST=postgres-user
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=user_database
      - MONGO_URI=mongodb://bonus-user-db:27017
    depends_on:
      postgres-user:
        condition: service_healthy
      bonus-user-db:
        condition: service_healthy
      user-service:
        condition: service_started
    restart: unless-stopped

  ielts-service:
    build:
      context: ./ielts-service
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    environment:
      - DB_HOST=postgres-ielts
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=ielts_database
    depends_on:
      postgres-ielts:
        condition: service_healthy
      integration-service:
        condition: service_started
      user-service:
        condition: service_started
    volumes:
      - voice_answers_data:/app/voice_answers
    restart: unless-stopped

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - ielts-service
      - integration-service
      - user-service
    restart: unless-stopped

volumes:
  postgres_ielts_data:
  postgres_user_data:
  redis_data:
  voice_answers_data:
  bonus_user_data:

networks:
  default:
    driver: bridge