definitions:
  models.CreateAnswer:
    properties:
      answers:
        items:
          type: string
        type: array
      sectionType:
        type: string
    required:
    - answers
    type: object
  pb.Answer:
    properties:
      bookId:
        type: integer
      id:
        type: integer
      sectionAnswer:
        items:
          type: string
        type: array
      sectionType:
        type: string
    type: object
  pb.GetAnswerResponse:
    properties:
      answers:
        items:
          $ref: '#/definitions/pb.Answer'
        type: array
    type: object
  utils.AbsResponse:
    properties:
      message:
        type: string
      statusCode:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/auth/login/{code}:
    post:
      consumes:
      - application/json
      description: Validate the authorization code and log in the user
      parameters:
      - description: Authorization Code
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/utils.AbsResponse'
        "400":
          description: Invalid code or login failed
          schema:
            $ref: '#/definitions/utils.AbsResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.AbsResponse'
      summary: User login via authorization code
      tags:
      - auth
  /api/ielts/answer/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve the answer associated with a specific book ID via gRPC.
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Answer found
          schema:
            $ref: '#/definitions/pb.GetAnswerResponse'
        "502":
          description: Error while gRPC connection
          schema:
            type: string
      summary: Get answer by book ID
      tags:
      - ielts-answer
  /api/ielts/answer/create/{bookId}:
    post:
      consumes:
      - application/json
      description: Create a new answer for a specified IELTS book
      parameters:
      - description: ID of the book
        in: path
        name: bookId
        required: true
        type: string
      - description: Answer content
        in: body
        name: answer
        required: true
        schema:
          $ref: '#/definitions/models.CreateAnswer'
      produces:
      - application/json
      responses:
        "200":
          description: Answer created successfully
          schema:
            $ref: '#/definitions/utils.AbsResponse'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/utils.AbsResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.AbsResponse'
      summary: Create a new answer for a book
      tags:
      - ielts-answer
  /api/ielts/answer/delete/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an answer by its ID
      parameters:
      - description: ID of the answer
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Answer deleted successfully
          schema:
            $ref: '#/definitions/utils.AbsResponse'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/utils.AbsResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.AbsResponse'
      summary: Delete an answer
      tags:
      - ielts-answer
  /api/ielts/book/books:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all IELTS books
      produces:
      - application/json
      responses:
        "200":
          description: List of books
          schema:
            $ref: '#/definitions/utils.AbsResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.AbsResponse'
      summary: Get all IELTS books
      tags:
      - ielts-book
  /api/ielts/book/create/{name}:
    post:
      consumes:
      - application/json
      description: Create a new book for IELTS exam preparation
      parameters:
      - description: Name of the book
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Book created successfully
          schema:
            $ref: '#/definitions/utils.AbsResponse'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/utils.AbsResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.AbsResponse'
      summary: Create a new IELTS book
      tags:
      - ielts-book
  /api/ielts/book/delete/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an IELTS book by its ID
      parameters:
      - description: ID of the book
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Book deleted successfully
          schema:
            $ref: '#/definitions/utils.AbsResponse'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/utils.AbsResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.AbsResponse'
      summary: Delete an IELTS book
      tags:
      - ielts-book
swagger: "2.0"
