// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/ielts.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IeltsService_CreateBook_FullMethodName = "/ielts.IeltsService/CreateBook"
)

// IeltsServiceClient is the client API for IeltsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IeltsServiceClient interface {
	CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*CreateBookResponse, error)
}

type ieltsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIeltsServiceClient(cc grpc.ClientConnInterface) IeltsServiceClient {
	return &ieltsServiceClient{cc}
}

func (c *ieltsServiceClient) CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*CreateBookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBookResponse)
	err := c.cc.Invoke(ctx, IeltsService_CreateBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IeltsServiceServer is the server API for IeltsService service.
// All implementations must embed UnimplementedIeltsServiceServer
// for forward compatibility.
type IeltsServiceServer interface {
	CreateBook(context.Context, *CreateBookRequest) (*CreateBookResponse, error)
	mustEmbedUnimplementedIeltsServiceServer()
}

// UnimplementedIeltsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIeltsServiceServer struct{}

func (UnimplementedIeltsServiceServer) CreateBook(context.Context, *CreateBookRequest) (*CreateBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBook not implemented")
}
func (UnimplementedIeltsServiceServer) mustEmbedUnimplementedIeltsServiceServer() {}
func (UnimplementedIeltsServiceServer) testEmbeddedByValue()                      {}

// UnsafeIeltsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IeltsServiceServer will
// result in compilation errors.
type UnsafeIeltsServiceServer interface {
	mustEmbedUnimplementedIeltsServiceServer()
}

func RegisterIeltsServiceServer(s grpc.ServiceRegistrar, srv IeltsServiceServer) {
	// If the following call pancis, it indicates UnimplementedIeltsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IeltsService_ServiceDesc, srv)
}

func _IeltsService_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IeltsServiceServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IeltsService_CreateBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IeltsServiceServer).CreateBook(ctx, req.(*CreateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IeltsService_ServiceDesc is the grpc.ServiceDesc for IeltsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IeltsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ielts.IeltsService",
	HandlerType: (*IeltsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBook",
			Handler:    _IeltsService_CreateBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ielts.proto",
}
