server:
  port: 50051

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "ielts_database"
  sslmode: "disable"


grpc:
  userService:
    address: "localhost:50052"
  integrationService:
    address: "localhost:50054"